definitions:
  model.Partner:
    properties:
      address_lat:
        type: number
      address_long:
        type: number
      flooring_materials:
        items:
          type: string
        type: array
      id:
        type: string
      operating_radius:
        type: integer
      rating:
        type: integer
    type: object
  partner.MatcherRequest:
    properties:
      address_lat:
        type: number
      address_long:
        type: number
      floor_area:
        type: number
      floor_material:
        type: string
      phone_number:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This service is responsible for managing partners.
  title: Partners API
  version: "1.0"
paths:
  /partners/:id:
    get:
      description: This endpoint retrieves a partner using its UUID.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Partner'
        "401":
          description: Unauthorized
          schema:
            type: error
        "403":
          description: Forbidden
          schema:
            type: error
        "404":
          description: Not Found
          schema:
            type: error
        "500":
          description: Internal Server Error
          schema:
            type: error
      summary: Get Partner
      tags:
      - Partners
  /partners/match:
    post:
      description: This endpoint is used to show customers the available partners
        within their radius
      parameters:
      - description: The match request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/partner.MatcherRequest'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Partner'
            type: array
        "401":
          description: Unauthorized
          schema:
            type: error
        "403":
          description: Forbidden
          schema:
            type: error
        "404":
          description: Not Found
          schema:
            type: error
        "500":
          description: Internal Server Error
          schema:
            type: error
      summary: Match Partners
      tags:
      - Partners
swagger: "2.0"
